### ISSUE TITLE
export of Key

### ISSUE THREAD

**Issue by flddr** [terrier989/curve25519#3]
I have a question; this package is exporting

https://github.com/terrier989/curve25519/blob/4ffc83fc27c52106a1cb8be650e16d3a8383d6cf/lib/src/key.dart#L37

but i guess there is no real need for exactly this name?

Using other packages, like https://pub.dev/packages/encrypt, where it makes much sense in user code, has a naming conflict, so we have to `import as` or `hide Key`.

As i didn't touch `Key` in the code itself, like in your example

```dart
import 'package:curve25519/curve25519.dart';

void main() async {
  // Let's generate two asymmetric keypair.
  final keypair1 = await X25519().generateKeyPair();
  final keypair2 = await X25519().generateKeyPair();

  // We can now calculate a shared secret using the (sender's) private key and
  // the (recipient's) public key.
  var sharedSecret = await X25519().calculateSharedSecret(
    keypair1.secretKey,
    keypair2.publicKey,
  );
  print("#1 -> #2: ${sharedSecret.toHex()}");

  sharedSecret = await X25519().calculateSharedSecret(
    keypair2.secretKey,
    keypair1.publicKey,
  );
  print("#2 -> #1: ${sharedSecret.toHex()}"); // Same as #1 --> #2
}
```

do you feel ok to rename it to avoid this conflict? Like `X25519Key` for example?

Again, thank you very much!

**Comment by terrier989** [comment]
Thanks for proposal!

Yes, the class could be renamed.

You could also use library prefix. For example:
```dart
'package:curve25519/curve25519.dart' as x25519;

void main() {
  x25519.Key key = ..
}
```

**Comment by flddr** [comment]
Renaming would help others as they do not need to look for those `as` :blush: 

Thank you :100:
